---
- name: 'Install database'
  apt:
    name: [ca-certificates]
    state: latest
  become: yes

- name: 'Install Postgresql'
  shell: '{{ item }}'
  args:
    warn: False
  with_items:
    - 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - 'curl -sSL http://packages.2ndquadrant.com/bdr/apt/AA7A6805.asc | apt-key add -'
    - 'apt -y update'
    - 'apt-get -y --install-suggests install postgresql-bdr-9.4-bdr-plugin'
    - 'curl -sSLo postgresql.conf https://s3.us-east-2.amazonaws.com/automatization-files/postgresql.conf'
    - 'chmod 640 pg_hba.conf'
    - 'chmod 644 postgresql.conf'
    - 'mv pg_hba.conf postgresql.conf /etc/postgresql/9.4/main/'
    - 'chown postgres:postgres /etc/postgresql/9.4/main/*'
    - 'systemctl restart postgresql'
    - 'su - postgres'
    - 'curl -sSLo sync-mon.sh https://s3.us-east-2.amazonaws.com/automatization-files/sync-mon.sh'
    - 'curl -sSLo replication-mon.sh https://s3.us-east-2.amazonaws.com/automatization-files/replication-mon.sh'
    - 'curl -sSLo active_users_apps-mon.sh https://s3.us-east-2.amazonaws.com/automatization-files/active_users_apps-mon.sh'
    - 'curl -sSLo pg_stat-mon.sh https://s3.us-east-2.amazonaws.com/automatization-files/pg_stat-mon.sh'
    - 'chmod 700 *.sh'
    - 'su - postgres'
    - 'createuser --no-replication -SDRElP vision'
    - 'createuser --replication -sDRElP wari_rep'
    - 'createuser --no-replication -SDRElP wari_ro'
    - 'createuser --no-replication -SDRElP wari_user'
    - 'createuser --no-replication -SDRElP wari_devs'
    - 'createdb --encoding=UTF-8 --owner=wari_user wari_db'
  become: yes
